### ISSUE TITLE
Can't get protractor to work

### ISSUE THREAD

**Issue by yleflour** [bamlab/ionic-CJS-boilerplate#1]
Protractor accepts coffeescript config files but doesn't recognizes this project's. Also, protractor doesn't seem to be able to connect to the server.

@BenjMichel Can you help?

**Comment by BenjMichel** [comment]
Protractor doesn't accept coffee config file. Either you transpile it first then run it or you write it directly in js. And FIY in the tests you have to use `By` instead of `by` because `by` is a keyword for CoffeeScript.
